# Generated by Django 5.1.4 on 2024-12-07 21:28

from django.db import migrations

def populate_role(apps, schemaedetior):
    entries = {
        "Product Owner": "The team member who defines requirements",
        "Developer": "The person on the team who works on issues",
        "Scrum Master": "The team's coach"
    }
    Role = apps.get_model("accounts", "Role")
    for key, value in entries.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [ 
        migrations.RunPython (populate_role)
    ]


